[workspace]
resolver = "3"
members = [
    "crates/daemon",
    "crates/actions",
    "crates/niri"
]

[workspace.dependencies]
anyhow = "1.0"
tokio = { version = "1.53.1", features = ["full"] }
niri-ipc = "=26.4.0"
serde_json = "1.0"
serde = { version = "1.0.229", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "std", "fmt"] }
dotenvy = "0.15"

[workspace.package]
edition = "2024"
rust-version = "1.95"
