[package]
name = "niqol-ui"
version = "0.1.0"
edition.workspace = true
rust-version.workspace  =true

[dependencies]
niqol-core = { path = "../core" }
niqol-ipc = { path = "../ipc" }
dotenvy.workspace = true
serde_json.workspace = true
serde.workspace = true
slint.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[build-dependencies]
slint-build = "1.18.1"

