[package]
name = "niqol-cli"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
tokio.workspace = true
niri-ipc.workspace = true
serde_json.workspace = true
serde.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
dotenvy.workspace = true
clap = { version = "4.6.6", features = ["derive"] }

[dev-dependencies]
tempfile = "3.27.0"
